### ISSUE TITLE
Feature request: Advanced Custom Fields support for comparing Rewritten pages

### ISSUE THREAD

**Issue by thorsimpson** [Yoast/duplicate-post#105]
When using the Compare tool for Rewrite & Republish, only changes to the page title and main content block seem to be visible.

Our site uses Advanced Custom Fields almost exclusively for our content, so the compare tool doesn't offer any insight as to what has changed.

Pages CAN be republished successfully using Advanced Custom Fields, we just need visibility into what changes have been made to these fields in order for the plugin to be fully functional.

Thank you for considering support of this feature.

**Comment by thorsimpson** [comment]
This will be great. Just waiting on testing?

**Comment by enricobattocchi** [comment]
@thorsimpson this is has been released in 4.1.2!
