### ISSUE TITLE
Feature request: URL change with republish

### ISSUE THREAD

**Issue by mwestenthanner** [Yoast/duplicate-post#113]
First off, thanks for the great plugin, this almost does a perfect job for our use case. However, I have a request to further enhance the republish feature. 

As a user that relies heavily on Google Discover, I want to:
- change the URL when I republish a post so that Google recognizes the new URL
- have the new post with the new URL overwrite the old post with the old URL
- ideally, the old URL would 301-redirect the user to the new post

Is this something that you have planned or even something that we can achieve already with a workaround?

**Comment by jono-alderson** [comment]
I'd be keen to dig into the use-case a little better; would you mind providing some additional context to help me understand?

- Could you explain why you want to change the URL?
- Am I right in understanding that this is the desired flow?
  - Old post at `/old-post/`
  -  Republished to `/new-post/`
  - 301 redirect implemented from `/old-post/` to `/new-post/`
- What's the special consideration for Google Disover here?

**Comment by mwestenthanner** [comment]
Of course, I'm happy to elaborate!

- We need to change the URL because our traffic doesn't come from classic SEO but from curated content feeds such as Google Discover and social media. These detect "new contents" primarily via the URL, and also the headline and meta text. So, we republish contents so that these get re-detected and included by those feeds.
- Our republish case is pretty much the opposite to the classic SEO case: we do not change the content of the actual article, but only the required parameters (URL, headline, teaser, meta information)
- Yes, exactly this flow is required for our case.

**Comment by jono-alderson** [comment]
Wow, that's a really interesting use-case!

I don't think it's something we're likely to support in the plugin(s), however, as it runs counter to almost all SEO use-cases, as you point out! As such, I'm going to close this issue. 

However... 

I think it should be possible to cobble something together which does this automagically, using existing filters/functions etc.

Have you experimented with hooking into the `save_post` action? I think the example at https://wordpress.stackexchange.com/a/105936 isn't a million miles away from what you need. That should also trigger the Yoast SEO slug change detection, which should handle the redirect for you.
