### ISSUE TITLE
Accessibility improvements for the "Delete reference to original item" checkbox

### ISSUE THREAD

**Issue by afercia** [Yoast/duplicate-post#17]
The new "Delete reference to original item" checkbox has room for a few quick accessibility improvements.

1
The checkbox label is a wrapping label (so called "implicit labelling). While this is perfectly valid from a technical side, some assistive technologies (especially old versions and speech recognition software) have problems with implicit labelling. That's the reason why [WordPress recommends explicit labelling](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/accessibility/#labeling), that is: a non-wrapping label associated with for / id attributes. The checkbox markup should be updated accordingly.

This applies to all the places where the checkbox is used: post box, quick edit, block editor.

2
In the Quick Edit form, the link to the original is not underlined. Users with low vision will barely recognize it's a link:

<img width="373" alt="Screenshot 2020-06-16 at 09 59 14" src="https://user-images.githubusercontent.com/1682452/84752109-a0d1b880-afbd-11ea-885e-b051dee26608.png">

It would be nice to override the WordPress CSS and just underline this link.

3
As also @enricobattocchi mentioned, the link placed _within_ the label may not be ideal. It's not a huge issue but, ideally, `<label>` elements should only contain the form element _name_, i.e. the "what is this?".

Current (pseudo) code:

`[checkbox] Delete reference to original item: [link]Hello World[/link]`

Ideally, the link should be moved out from the `<label>` element and placed _after_ it. Maybe referenced with an `aria-describedby` attribute. Pseudo code:

`[checkbox aria-describedby="xyz"] Delete reference to original item.`
`[span id="xyz"]The original item this was copied from is  [link]Hello World[/link][/span]`

Better wording welcome.

**Comment by enricobattocchi** [comment]
All of the above makes perfect sense, but there's a problem regarding the WordPress styles in the Quick Edit. The plugin adds some HTML that was written following the examples of the other checkboxes, but unfortunately WordPress is using `label` tags to set the position of the checkboxes.
Pulling the checkbox and the link out of the `label` tag we get something like that:
![Screenshot_2020-06-16 Posts ‹ Basic — WordPress](https://user-images.githubusercontent.com/15989132/84782177-05a20880-afe8-11ea-9303-c7d8b8ae839f.png)

We should avoid using extensive inline styles.
Instead, we could use the already existing `duplicate-post.css`. Currently it's enqueued only when the button in the admin bar is present (depending on an option).
We need styles for:

- checkbox, label, description with link in the Quick Edit
- link in the metabox

The CSS file would be enqueued:
- in the Post List, for selected users and post types
- in the Edit screen, for selected users and post types

I will proceed to submit PR on this.

**Comment by enricobattocchi** [comment]
Filed a PR along the guidelines above.

The content for the Metabox is used both with Classic Editor and Block Editor, and it looks like there are some inconsistencies with the latter regarding the alignment of the label with the checkbox:

![Screenshot_2020-06-17 Edit Post ‹ Basic — WordPress](https://user-images.githubusercontent.com/15989132/84888406-89ff9480-b097-11ea-9bb0-2040cefd7a2c.png)
![Screenshot_2020-06-17 Edit Movies ‹ Basic — WordPress](https://user-images.githubusercontent.com/15989132/84888411-8c61ee80-b097-11ea-9e8d-9fea436798c1.png)

I think we can leave out this problem since probably there will be a complete redesign to adapt the plugin to the Block Editor.

**Comment by enricobattocchi** [comment]
PR merged.
