### ISSUE TITLE
Need an action hook in the create_duplicate method

### ISSUE THREAD

**Issue by methnen** [Yoast/duplicate-post#184]
Wondering if it would be possible to get an action added?

I’ve got a custom post type where some additional stuff needs to happen AFTER the new post id is known. There’s currently no way to do this and it’s making some of my staff miserable.

Something like this in the second to last line of code in the `create_duplicate` function inside of `class-post-duplicator.php` file would be perfect. We’d know the old post ID as well as the new on and be able to do all of the things we need from there.

```php
\do_action( 'duplicate_post_create_duplicate_end', $new_post_id, $post->ID );
```

Hopefully that’s something that’s possible?

**Comment by gin0115** [comment]
I needed access to similar and there are hooks fired after a duplicate post or page is created.

`do_action( 'duplicate_post_post_copy', $new_post_id, $post, $status, $parent_id );`

It's around lines 760 of admin_functions.php

There are 2 other actions fired just prior to that for post & page duplication specifically. 

(Found your issue while looking for a solution that needed a similar hook, but thought I'd share this here if it helps you too.)

**Comment by methnen** [comment]
Awesome, thanks for noting that. When looking through the code I somehow missed that hook entirely. 

I think that will probably work for what I need to do. 

I'll certainly give it a try and see it works out.

Thanks again.

**Comment by methnen** [comment]
Just some follow up, the action hook @gin0115 mentioned was sufficient for our needs so I guess I rescind my request. :)
