### ISSUE TITLE
Post status "dp-rewrite-republish" slows down WordPress

### ISSUE THREAD

**Issue by ivptr** [Yoast/duplicate-post#211]
Is it possible to completely remove "dp-rewrite-republish" post status, because it adds overhead to WordPress queries?

For example, if you access https://www.mysite.com/robots.txt the following query is executed:

```
SELECT 
  SQL_CALC_FOUND_ROWS wp_posts.ID 
FROM 
  wp_posts 
WHERE 
  1 = 1 
  AND wp_posts.post_type = 'post' 
  AND (
    wp_posts.post_status = 'publish' 
    OR wp_posts.post_status = 'dp-rewrite-republish'
  ) 
ORDER BY 
  wp_posts.post_date DESC 
LIMIT 
  0, 10
```

Such query takes 0.5762 seconds on WordPress having 850k records in wp_posts table.

If we remove ```OR wp_posts.post_status = 'dp-rewrite-republish'``` the query takes 0.0013 seconds.

The first query is using filesort and the second doesn't:

```
EXPLAIN SELECT wp_posts.ID FROM wp_posts WHERE 1=1  AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'dp-rewrite-republish')  ORDER BY wp_posts.post_date DESC LIMIT 0, 10;
+------+-------------+----------+-------+------------------+------------------+---------+------+--------+------------------------------------------+
| id   | select_type | table    | type  | possible_keys    | key              | key_len | ref  | rows   | Extra                                    |
+------+-------------+----------+-------+------------------+------------------+---------+------+--------+------------------------------------------+
|    1 | SIMPLE      | wp_posts | range | type_status_date | type_status_date | 164     | NULL | 413436 | Using where; Using index; Using filesort |
+------+-------------+----------+-------+------------------+------------------+---------+------+--------+------------------------------------------+
```
```
EXPLAIN SELECT wp_posts.ID FROM wp_posts WHERE 1=1  AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish')  ORDER BY wp_posts.post_date DESC LIMIT 0, 10;
+------+-------------+----------+-------+------------------+------------------+---------+---------------+--------+--------------------------+
| id   | select_type | table    | type  | possible_keys    | key              | key_len | ref           | rows   | Extra                    |
+------+-------------+----------+-------+------------------+------------------+---------+---------------+--------+--------------------------+
|    1 | SIMPLE      | wp_posts | ref   | type_status_date | type_status_date | 164     | const,const   | 413436 | Using where; Using index |
+------+-------------+----------+-------+------------------+------------------+---------+---------------+--------+--------------------------+
```

Meaning ```OR wp_posts.post_status = 'dp-rewrite-republish'``` in added to all queries where fetching wp_posts takes place, making the whole WordPress slower.

No reason to slow down frontend because we are using backend plugin.

**Comment by lkraav** [comment]
I also see `OR wp_posts.post_status = 'dp-rewrite-republish'` added to all frontend queries. Can @enricobattocchi enlighten us what's going on?

**Comment by enricobattocchi** [comment]
Thank you for your detailed report! It was an oversight on our side: we have a fix ready, aiming to release a new version including it in the next few weeks.

**Comment by ivptr** [comment]
@enricobattocchi many thanks for fixing frontend speed.

Unfortunately, "dp-rewrite-republish" post status is still present, meaning it will still slow down backend.

Other plugins for post duplication do not register their own post status.

**Comment by enricobattocchi** [comment]
@ivptr the fix hasn't been released yet, did you test the RC?

**Comment by enricobattocchi** [comment]
@ivptr the custom post status is used by the Rewrite & Republish which, as far as I know, is provided only by our plugin. So things cannot really be compared. Anyway it shouldn't impact performances since with the fix is used only temporarily (usually 1-2 seconds) while the post is being republished.

**Comment by ivptr** [comment]
When listing posts in the backend (/wp-admin/edit.php) I see 'dp-rewrite-republish' in queries:
```
SELECT COUNT( 1 )
FROM wp_posts
WHERE post_type = 'post'
AND post_status NOT IN ( 'trash','auto-draft','inherit','request-pending','request-confirmed','request-failed','request-completed','dp-rewrite-republish' )
AND post_author = 1
```
```
SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  WHERE 1=1  AND wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'dp-rewrite-republish' OR wp_posts.post_status = 'future' OR wp_posts.post_status = 'draft' OR wp_posts.post_status = 'pending' OR wp_posts.post_status = 'private')  ORDER BY wp_posts.post_date DESC LIMIT 0, 50
```
