### ISSUE TITLE
Cloning link in frontend

### ISSUE THREAD

**Issue by toniojst** [Yoast/duplicate-post#225]
Hi, i try this plugin and function `<?php duplicate_post_clone_post_link( $link, $before, $after, $id ); ?>` on frontend, but problem is that when i click this created link i redirected to Edit page of cloned post. So i get link
`".../wp-admin/admin.php?action=duplicate_post_new_draft&post=ID&_wpnonce=NONCE" `
buut i want to get link like 
`".../wp-admin/admin.php?action=duplicate_post_clone&post=ID&_wpnonce=NONCE"`

What is solution is here.

**Comment by jeroenrotty** [comment]
We use GitHub exclusively for well-documented bug reports or feature requests. The reported issue does not contain enough information to be a viable bug report or feature request. Thus, we're now closing the report.

We have the following support channels:
- [Help Center](https://yoast.com/help/)
- [Support Forums](https://wordpress.org/support/plugin/duplicate-post) on [WordPress.org](https://wordpress.org/)

If you feel like your bug or enhancement is valid and should be reviewed by us, please use the provided templates, read our [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md), and submit a new issue.

Thank you for your understanding.
