### ISSUE TITLE
problems activating the plugin.

### ISSUE THREAD

**Issue by JimKnopf128** [Yoast/duplicate-post#231]
I don't know nothing.

I was encouraged to report issues I have. A site I manage auto-updated to wp 5.9 last night. After some troubleshooting, I identified 2/9 plugins causing issues, YOAST duplicate-post being one of them:

I receive the following after I activate the plugin:
Fatal error: Allowed memory size of 41943040 bytes exhausted (tried to allocate 36864 bytes) in /raid/home/harmony/harmonyfdn/wp-admin/includes/admin.php on line 89

running INSPIRO theme (1.6.2 updated this morning)

I don't know what is related to what, if at all, but I thought I mention it. Cheers.

**Comment by jeroenrotty** [comment]
Hey @JimKnopf128,

That error says there wasn't enough free memory available for what your site/plugin/theme needed. Please check with your web host if you still have this issue on the newest versions of all plugins, themes and WordPress.
