### ISSUE TITLE
Missing translations in Gutenberg editor

### ISSUE THREAD

**Issue by petitphp** [Yoast/duplicate-post#233]
Even after downloading translations for the plugin, buttons in the publish panel in Gutenberg editor remain in english.
<img width="260" alt="without_set_script_translations" src="https://user-images.githubusercontent.com/158572/154733054-8f74d322-d31e-4c04-b08d-6ffc21682784.png">
Calling `wp_set_script_translations` with the editor script handle and the plugin textdomain fix the issue.
<img width="262" alt="with_set_script_translations" src="https://user-images.githubusercontent.com/158572/154733087-d2b70a68-c2ac-4b56-aad6-44d81f9d7c61.png">

**Comment by trinermedia** [comment]
@enricobattocchi This fix is still not released, right? 
By the way, other strings are also affected, e.g. the “Republish” button and the message below.
<img width="280" alt="republish button and message in gutenberg" src="https://github.com/user-attachments/assets/ea045190-ce14-4c65-9cf0-9246d7c1d3ba">
