### ISSUE TITLE
Duplicating custom post type overrides fields

### ISSUE THREAD

**Issue by criting** [Yoast/duplicate-post#235]
We have a custom post type called People and every profile there is assigned as an author to the default post type Posts.

If for example Person 1 is an author of Post ID 123, when you duplicate Person 1, the duplicated Person is now the author of Post ID 123 and the original one that was duplicated is now not an author or any post.

Is there a way to fix that?

**Comment by jeroenrotty** [comment]
Hey!

Yes, you can disable the checkbox on "what to copy over" under Settings > Duplicate Post. You can uncheck "author".
