### ISSUE TITLE
Copy wrong contents 

### ISSUE THREAD

**Issue by ejesgist** [Yoast/duplicate-post#256]
The plugin keep coping wrong or past contents.

I used the plugin to  duplicate post titled " Week 49 pool code add few adjustments  and published the post as week 50 pool code ...I used the plugin to duplicate week 50 pool code so I can post week 51 Pool code. 

I discovered when I duplicate week 50 pool code the contents on the post keep showing week 18 pool code contents "  instead of contents of week 50 pool code. 

I keep having these errors for other posts ....

**Comment by jeroenrotty** [comment]
Hey @ejesgist,

Hmm. I'm not sure I completely understand. When you clone a post or page, it _should_ clone the current state and content of that item, so it's really weird it wouldn't do that for you. Does it still happen when everything is up to date on your site? If so, please let us know the steps to reproduce. I'm not able to replicate similar behavior.
