### ISSUE TITLE
Rewrite tag `%pagename%` is shown in the url while republishing the post

### ISSUE THREAD

**Issue by shreyasikhar** [Yoast/duplicate-post#292]
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Step-by-step reproduction instructions
1. Select any pretty permalink from Settings-> Permalinks
2. Go to Pages and click on Rewrite and Republish on one of the page post. (Refer to the below screencast)

https://user-images.githubusercontent.com/40795917/224995848-5b005722-b211-4f45-b852-817d3718b100.mov

This issue appears on custom post types and pages. 
It is reproducible with WordPress default themes and plugin `Yoast Duplicate Post` active. 

#### Expected results
1. http://test-yoast-single.local/sample-page-2/

#### Actual results
1. http://test-yoast-single.local/%pagename%/

### Screenshots, screen recording, code snippet
If possible, please provide a screenshot, a screen recording or a code snippet which demonstrates the bug.

### Technical info

* If relevant, which editor is affected (or editors): 
- [x] Block Editor
- [x] Gutenberg Editor
- [ ] Classic Editor 
- [ ] Other: 

* Which browser is affected (or browsers): 
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Other: 

#### Used versions
* Device you are using: Macbook Air M1
* Operating system: MacOS Ventura
* PHP version: 8.1
* WordPress version: 6.1.1
* WordPress Theme: 2023 theme
* Yoast Duplicate Post version: 4.5

**Comment by shreyasikhar** [comment]
After debugging on the root cause of the issue, I have found that it is coming from Gutenberg core and the issue is tracked here https://github.com/WordPress/gutenberg/issues/29477

**Comment by jeroenrotty** [comment]
Hey @shreyasikhar,
Thank you for the issue and detailed information.
So the issue relies in Gutenberg, and it was merged/fixed upstream. I'll be closing the issue for now.
