### ISSUE TITLE
'Documentation' plugin link should use shortcode

### ISSUE THREAD

**Issue by jeroenrotty** [Yoast/duplicate-post#299]
Moved from: https://yoast.atlassian.net/browse/IM-1656
Reporter: @jonoalderson 

### Please give us a description of what happened

The 'Documentation' link in the plugin info should use a short link. It should be changed from https://yoast.com/wordpress/plugins/duplicate-post/ to https://yoa.st/4jr.
![ysp-doc-link](https://user-images.githubusercontent.com/7323966/228817571-017f71af-9b41-498f-9878-538b32cda672.png)

**Comment by masteradhoc** [comment]
@jeroenrotty / @jonoalderson please review :)
