### ISSUE TITLE
Fork & merge post

### ISSUE THREAD

**Issue by jdevalk** [Yoast/duplicate-post#41]
As a user, I want to be able to:

* Fork a post (or page, or another custom post type) and then merge it with its original once I'm done with it, so I want to make a copy of the post with the clear intention to merge it back into the original.
* I want to maintain both the original edit history and the "new" edit history.
* I want to be able to run my full editorial process (draft, review, publish).
* Once I hit "Merge & publish" (or whatever the name of the button should be) I want the fork to replace the original. 

Questions to consider:
* If the original changed since the fork, can we easily display a merge interface using the revision interface?
* Should we call this "fork & merge" or is that too geeky and would normal users give this type of functionality a different name?

Relations to other products to consider:
* Yoast SEO should be smart enough to realize this is a fork and shouldn't whine about the fact that we're using a focus keyword twice.
* Yoast SEO Premium shouldn't make any redirects etc on publication.

**Comment by roborourke** [comment]
FWIW in Altis we modified the naming to be "Create Amendment", then "Publish Amendment" etc... Fork & merge are definitely terms that are familiar to us as developers but maybe not so much for non technical users.

**Comment by jeroenrotty** [comment]
This is what the Rewrite & Republish feature has become. Closing.
