### ISSUE TITLE
problems with Version 4.0.2 

### ISSUE THREAD

**Issue by DoronYosha** [Yoast/duplicate-post#99]
Hi there
Just to inform you,
I updated the plugin Yoast Duplicate Post - to Version 4.0.2 and since then I'm getting these errors on my admin

The first argument should be either a string or an integer in /home/customer/www/gobeetravel.com/public_html/wp-content/plugins/duplicate-post/src/ui/class-post-list.php
 on line 109

Warning: Illegal offset type in /home/customer/www/gobeetravel.com/public_html/wp-content/plugins/duplicate-post/src/ui/class-post-list.php
 on line 113

Warning: array_keys() expects parameter 1 to be array, null given in /home/customer/www/gobeetravel.com/public_html/wp-content/plugins/duplicate-post/src/ui/class-post-list.php
 on line 63

Warning: array_merge(): Expected parameter 2 to be an array, null given in /home/customer/www/gobeetravel.com/public_html/wp-content/plugins/duplicate-post/src/ui/class-post-list.php
 on line 63  

when I downgrade it works good,
Thanks
Doron

**Comment by Djennez** [comment]
@DoronYosha are you by any chance running Rankmath + Elementor on your site? If not, can you run a conflict check to see which plugin causes these errors in the Duplicate Post plugin? This is a compatibility issue, and the 2 earlier mentioned plugins show up pretty often.

**Comment by DoronYosha** [comment]
Hi
Yes, I use  Rankmath + Elementor

**Comment by Djennez** [comment]
Thanks for the info!

Internal duplicate report: https://yoast.atlassian.net/browse/QAK-2596

**Comment by DoronYosha** [comment]
Hi
I didn't really understand what next :-)

**Comment by Djennez** [comment]
Nothing much, this will likely get fixed in one of the next updates.

**Comment by DoronYosha** [comment]
ok, Thank you!

**Comment by iamazik** [comment]
+1 for https://wordpress.org/support/topic/php-warning-272/

**Comment by jeroenrotty** [comment]
This should have been fixed in DP 4.1 as the internal notes. Closing.
